server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    username: postgres
    password: root
  application:
    name: resources
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
          jwt:
            issuer-uri: http://localhost:9000
      auth-server:
        base-uri: http://127.0.0.1:9000
    cors:
      allowed-origin: '*'
      allowed-method: 'POST,GET'
      max-age: '3600'
      allowed-header: 'x-requested-with,authorization,content-type'

logging:
  level:
    org:
      springframework:
        security: TRACE


springdoc:
  swagger-ui:
  openapi:
    server:
      url: ''
      description: ''
    contact:
      name: 'Contact Name'
      email: 'contact@correo.com'
    info:
      title: 'BaseAPI '
      version: '1.0'
      description: 'Documentación de la API '
